production:
  adapter: <%= ENV["DB_ADAPTER"] || 'mysql2' %>
  host: <%= ENV["DB_HOST"] %>
  database: <%= ENV["DB_DATABASE"] || 'brimir' %>
  username: <%= ENV["DB_USER"] || 'brimir' %>
  password: <%= ENV["DB_PASSWORD"] %>
